version: "3"

services:
  m3dbnode_1:
    image: m3dbnode-local
    depends_on:
      - "etcd"
    hostname: m3dbnode_1
    volumes:
      - /home/user/m3_data/1/m3db:/var/lib/m3db
      - /home/user/m3_data/1/m3kv:/var/lib/m3kv
  m3dbnode_2:
    image: m3dbnode-local
    depends_on:
      - "etcd"
    hostname: m3dbnode_2
    volumes:
      - /home/user/m3_data/2/m3db:/var/lib/m3db
      - /home/user/m3_data/2/m3kv:/var/lib/m3kv
  m3dbnode_3:
    image: m3dbnode-local
    depends_on:
      - "etcd"
    hostname: m3dbnode_3
    volumes:
      - /home/user/m3_data/3/m3db:/var/lib/m3db
      - /home/user/m3_data/3/m3kv:/var/lib/m3kv
  m3dbnode_4:
    image: m3dbnode-local
    depends_on:
      - "etcd"
    hostname: m3dbnode_4
    volumes:
      - /home/user/m3_data/4/m3db:/var/lib/m3db
      - /home/user/m3_data/4/m3kv:/var/lib/m3kv

  etcd:
    image: quay.io/coreos/etcd
    ports:
      - 2379:2379
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
