version: "3.5"
services:
  dbnode01:
    expose:
      - "9000-9004"
    ports:
      - "0.0.0.0:9000-9004:9000-9004"
    networks:
      - backend
    image: "m3dbnode_integration:${REVISION}"
    depends_on:
      - etcd
  coordinator01:
    expose:
      - "7201"
      - "7203"
      - "7204"
    ports:
      - "0.0.0.0:7201:7201"
      - "0.0.0.0:7203:7203"
      - "0.0.0.0:7204:7204"
    networks:
      - backend
    image: "m3coordinator_integration:${REVISION}"
    volumes:
      - "./cold_writes_simple:/etc/m3coordinator/"
    depends_on:
      - etcd
networks:
  backend: null
