version: "3.5"
services:
  dbnode01:
    expose:
      - "9000-9004"
    ports:
      - "0.0.0.0:9000-9004:9000-9004"
    networks:
      - backend
    image: "m3dbnode_integration:${REVISION}"
    depends_on:
      - etcd
  coordinator01:
    expose:
      - "7201"
      - "7203"
    ports:
      - "0.0.0.0:7201:7201"
      - "0.0.0.0:7203:7203"
    networks:
      - backend
    image: "m3coordinator_integration:${REVISION}"
    volumes:
      - "./m3coordinator01.yml:/etc/m3coordinator/m3coordinator.yml"
    depends_on:
      - etcd
  dbnode02:
    expose:
      - "19000-19004"
    ports:
      - "0.0.0.0:19000-19004:9000-9004"
    networks:
      - backend
    image: "m3dbnode_integration:${REVISION}"
    depends_on:
      - etcd
  coordinator02:
    expose:
      - "17201"
      - "17203"
    ports:
      - "0.0.0.0:17201:7201"
      - "0.0.0.0:17203:7203"
    networks:
      - backend
    image: "m3coordinator_integration:${REVISION}"
    volumes:
      - "./m3coordinator02.yml:/etc/m3coordinator/m3coordinator.yml"
    depends_on:
      - etcd
networks:
  backend: null
